### ISSUE TITLE
[Bug] Variable to use different table names doesn't work as expected pendo_<default_source_table_name>_identifier:

### ISSUE THREAD

**Issue by RichardThRivera** [fivetran/dbt_pendo_source#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

GROUP is a reserved word in Snowflake, so when trying to run the Pendo_Source package it fails due to Fivetran creating the source table as db.schema. "GROUP".

Used the variable above "pendo_group_identifier: '"GROUP"' and receive an error when trying to build the first temp model for pendo groups.

### Relevant error log or model output

```shell
21:15:20  Began running node model.pendo_source.stg_pendo__group_tmp
21:15:20  6 of 34 START sql view model dbt_rrivera_PENDO_SOURCE_STG_PKG.stg_pendo__group_tmp  [RUN]
21:15:20  Acquiring new snowflake connection "model.pendo_source.stg_pendo__group_tmp"
21:15:20  Began compiling node model.pendo_source.stg_pendo__group_tmp
21:15:20  Compiling model.pendo_source.stg_pendo__group_tmp
21:15:20  Writing injected SQL for node "model.pendo_source.stg_pendo__group_tmp"
21:15:20  finished collecting timing info
21:15:20  Began executing node model.pendo_source.stg_pendo__group_tmp
21:15:20  Using snowflake connection "model.pendo_source.stg_pendo__group_tmp"
21:15:20  On model.pendo_source.stg_pendo__group_tmp: /* {"app": "dbt", "dbt_version": "1.3.2", "profile_name": "user", "target_name": "DEV", "node_id": "model.pendo_source.stg_pendo__group_tmp"} */
show parameters like 'query_tag' in session
21:15:20  Opening a new connection, currently in state closed
21:15:22  SQL status: SUCCESS 1 in 1.8 seconds
21:15:22  Setting query_tag to 'stg_pendo__group_tmp'. Will reset to '' after materialization.
21:15:22  Using snowflake connection "model.pendo_source.stg_pendo__group_tmp"
21:15:22  On model.pendo_source.stg_pendo__group_tmp: /* {"app": "dbt", "dbt_version": "1.3.2", "profile_name": "user", "target_name": "DEV", "node_id": "model.pendo_source.stg_pendo__group_tmp"} */
alter session set query_tag = 'stg_pendo__group_tmp'
21:15:22  SQL status: SUCCESS 1 in 0.13 seconds
21:15:22  Writing runtime sql for node "model.pendo_source.stg_pendo__group_tmp"
21:15:22  Using snowflake connection "model.pendo_source.stg_pendo__group_tmp"
21:15:22  On model.pendo_source.stg_pendo__group_tmp: /* {"app": "dbt", "dbt_version": "1.3.2", "profile_name": "user", "target_name": "DEV", "node_id": "model.pendo_source.stg_pendo__group_tmp"} */
create or replace  view EDW_DEV_DB.dbt_rrivera_PENDO_SOURCE_STG_PKG.stg_pendo__group_tmp
  
   as (
    select * 
from edw_common_stg_db.pendo.group
  );
21:15:22  Snowflake adapter: Snowflake query id: 01a99b9b-0402-67b2-0022-a4030ac614be
21:15:22  Snowflake adapter: Snowflake error: 001003 (42000): SQL compilation error:
syntax error line 5 at position 29 unexpected 'group'.
syntax error line 6 at position 2 unexpected ')'.
21:15:22  finished collecting timing info
21:15:22  On model.pendo_source.stg_pendo__group_tmp: Close
21:15:22  Database Error in model stg_pendo__group_tmp (models/tmp/stg_pendo__group_tmp.sql)
  001003 (42000): SQL compilation error:
  syntax error line 5 at position 29 unexpected 'group'.
  syntax error line 6 at position 2 unexpected ')'.
  compiled Code at target/run/pendo_source/models/tmp/stg_pendo__group_tmp.sql
21:15:22  Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'ec0f282f-38f0-4dab-bd89-e0285877a691', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f4582cc4cd0>]}
21:15:22  6 of 34 ERROR creating sql view model dbt_rrivera_PENDO_SOURCE_STG_PKG.stg_pendo__group_tmp  [ERROR in 2.35s]
21:15:22  Finished running node model.pendo_source.stg_pendo__group_tmp
```

### Expected behavior

SQL for the temp table stg_pendo__group_tmp to use "GROUP" instead of group

### dbt Project configurations

`vars:
  #------ internal vars used by usertesting dbt models (alpha order)
  arr_reporting_start_date: "2018-12-01"  # start date for calculating / reporting arr
  docebo_start_date : "2021-03-31" #date when docebo started began
  employee_metrics_eom_logic_change: "2022-03-31" #Date where end of month snapshot started
  employee_team_snapshot_start: "2022-05-31" #Date where we add team field to employee snapshot
  flex_pricing_model_start_date: "2020-09-18" #Flex Pricing model was offically launched on the given date
  history_database: "EDW_COMMON_STG_DB"   #Snapshot History DB
  implementation_services_start_date: "2021-12-20"
  netsuite_implementation_date: "2021-10-01" #Date where Netsuite revenue data started populating
  seat_assignment_start_date: "2021-01-01" #Date from when seat assignment is populated in customer metrics
  sfdc_cpq_start_date: "2021-05-17"        # if opportunities closed after this date, they use salesforce CPQ
  sdfc_cpq_test_account_id: 675784
  ut_events_start_date: "2020-01-01"
  ut_events_start_year : "2021"   #Pulling data from segment
  video_start_date: "2018-01-01"
  netsuite_valid_date: "2022-01-01"
  netsuite_manual_adjustments_valid_date: "2022-09-01"
  skilljar_docebo_date: "2021-02-01" # date when skilljar discontinued and switched to docebo system
  surrogate_key_treat_nulls_as_empty_strings: true
  pendo_source:
    pendo_group_identifier: '"GROUP"'`

### Package versions

packages:  
  - package: dbt-labs/audit_helper
    version: [">=0.5.0", "<0.7.0"]

  - package: dbt-labs/codegen
    version: 0.9.0

  - package: entechlog/dbt_snow_mask
    version: 0.2.3

  - package: fivetran/fivetran_log
    version: [">=0.6.0","<0.8.0"]

  - package: fivetran/greenhouse
    version: 0.5.0

  #- package: fivetran/jira
  #  version: 0.9.0

  - package: dbt-labs/segment
    version: 0.9.0

  - package: fivetran/zendesk
    version: 0.10.0

  - package: fivetran/pendo
    version: 0.3.0

### What database are you using dbt with?

snowflake

### dbt Version

1.3.0

### Additional Context

![image](https://user-images.githubusercontent.com/79607656/212185725-7ec25bc8-00c1-421b-8274-2458289bd0e4.png)

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-catfritz** [comment]
Hi @RichardThRivera, I was able to take a closer look at this issue, and could you confirm a few things for me? The logic for this package should account for the reserved word "GROUP" in snowflake, but there is a known conflict if you try to use exactly "GROUP" in the identifier. If you run your model with the identifier variable completely removed, do you still get an error?

I tested out on our end, and I was able to replicate the error when setting var `pendo_group_identifier: "GROUP"`, but when I removed the variable entirely, the issue resolved. 

If you are still getting an error, could you confirm if your Snowflake set up to use all caps or does it allow mixed case? If you are still getting an error and your Snowflake uses mixed case, there are some other things I would like to check into, so please let me know how this goes!

**Comment by RichardThRivera** [comment]
I'll take a look and update you probably tomorrow

**Comment by fivetran-catfritz** [comment]
Hi @RichardThRivera sorry for the spam, but I was looking again into this and think I found another solution. I had success adding the below to my `dbt_project.yml` to turn identifier quoting on and be able to use the `pendo_group_identifier` var.

```yml
vars: 
  pendo_group_identifier: '"GROUP"'
quoting:
  identifier: true
```

Let me know if either of those work for you if you get a chance!

**Comment by RichardThRivera** [comment]
No that's all good, where in the project.yml am I making that setting..
because everytime I try it's erroring out

Thanks!
--

Richard Rivera
Data Warehouse Manager - Enterprise Systems

UserTesting – Real. Human. Insight.

M: (757) 784 - 4727

**Comment by fivetran-catfritz** [comment]
Hi @RichardThRivera,

My dbt_project.yml is set up like this:
![Screenshot 2023-02-07 at 5 10 17 PM](https://user-images.githubusercontent.com/111930712/217388072-322c3f71-cb7d-40fe-8760-b9928c8fe2b7.png)

One other thing to note is that if you already have a vars section in your yml, put the identifier under that section instead of making a 2nd vars section. 

Also if you're still having an error, it might be easier for us to work through the problem live. We have office hours that you can book with us via [this link](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours?month=2023-02), and then just link this issue instead of the community post the scheduler asks for. And also please include the current error if it's different from before. 

In the meantime, I'm going to release an update to the readme, but I still would like to work through this issue in hopes of finding a more robust solution!

**Comment by fivetran-joemarkiewicz** [comment]
Closing this issue as PR #19 addresses the initial issue identified in this bug report.
