### ISSUE TITLE
[Bug] Add _fivetran_id to primary key for feature_event and page_event tables

### ISSUE THREAD

**Issue by naveedd11** [fivetran/dbt_pendo_source#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Is unique tests are failing for both stg_pendo__feature_event and stg_pendo__page_event tables. The reason is due to an issue that occurred with the pendo fivetran source. Engineering added in a new _fivetran_id column to resolve the not unique issue. Don't we also need to add the new field into the surrogate key for both the tables in order to ensure that the test works?

### Relevant error log or model output

```shell
Failure in test unique_stg_pendo__feature_event_feature_event_key (models/stg_pendo.yml)
Got 23080 results, configured to fail if != 0
 
compiled Code at target/compiled/pendo_source/models/stg_pendo.yml/unique_stg_pendo__feature_event_feature_event_key.sql
 
Failure in test unique_stg_pendo__page_event_page_event_key (models/stg_pendo.yml)
Got 846243 results, configured to fail if != 0
 
compiled Code at target/compiled/pendo_source/models/stg_pendo.yml/unique_stg_pendo__page_event_page_event_key.sql
```

### Expected behavior

No test errors...

### dbt Project configurations

  pendo_database: kentik-monitoring
  pendo_schema: pendo
  pendo__visitor_history_pass_through_columns: # will be passed to pendo__visitor, pendo__feature_event, and pendo__page_event 
    - name:           "agent_name"
      alias:          "visitor_name"
    - name:           "agent_email"
      alias:          "visitor_email"
  pendo__account_history_pass_through_columns: # will be passed to pendo__account, pendo__feature_event, and pendo__page_event
    - name:           "agent_name"
      alias:          "account_name"  

### Package versions

packages:

  - package: dbt-labs/dbt_utils
    version: 0.8.6

  - package: fivetran/pendo
    version: 0.2.1
    
  - package: fivetran/salesforce_formula_utils
    version: [">=0.7.0", "<0.8.0"]

  - package: dbt-labs/codegen
    version: 0.8.0

  - package: dbt-labs/audit_helper
    version: 0.5.0 

### What database are you using dbt with?

bigquery

### dbt Version

1.3.0

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @naveedd11 thanks so much for opening this issue. 

We are currently evaluating this connector change on our end and working to update the test to be in alignment with the new connect surrogate key for uniqueness. I will post back once we are a working branch to test and validate before including in the next release.

**Comment by fivetran-joemarkiewicz** [comment]
I just wanted to post back with a quick update. This will likely be something our team will fold into our next sprint (starting next Thursday). You can expect to hear back from us then with more details. Thanks!

**Comment by naveedd11** [comment]
Thank you for the quick response and the update @fivetran-joemarkiewicz!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @naveedd11 did you intend to close this issue?

**Comment by naveedd11** [comment]
@fivetran-joemarkiewicz  Yup, it looks like y'all are working on it. Should i keep it open?

**Comment by fivetran-joemarkiewicz** [comment]
Yeah we are working on it but can close this out once the update is rolled out to the next release. I will reopen until we address this issue. Thanks!

**Comment by fivetran-catfritz** [comment]
Hi @naveedd11, I have created a test branch for you to try out. You can use the below in place of the dbt_pendo section of your `packages.yml`. Please let me know if this resolves your issue or if you have any feedback!

```yml
packages:
  - git: https://github.com/fivetran/dbt_pendo.git
    revision: test/add_fivetran_id
    warn-unpinned: false
```

**Comment by naveedd11** [comment]
Hey @fivetran-catfritz I tried replacing the package with what you had sent above but was met with a version error for the fivetran_formula_utils package

**Comment by naveedd11** [comment]
Great success!! 
<img width="299" alt="Screen Shot 2023-03-08 at 12 16 45 PM" src="https://user-images.githubusercontent.com/90706359/223783476-29f2c2d6-3d73-4c21-8a9a-d6412ba81c14.png">

**Comment by fivetran-catfritz** [comment]
Awesome! Thanks @naveedd11 for testing this out. We will be releasing an updated version with this later today!

**Comment by fivetran-catfritz** [comment]
The latest version is now released! Install using the following code, so it will automatically catch minor updates:
```yml
packages:
  - package: fivetran/pendo
    version: [">=0.4.0", "<0.5.0"]
```
