### ISSUE TITLE
Remove time zone before datediff

### ISSUE THREAD

**Issue by everettttt** [fivetran/dbt_pendo_source#9]
See [here](https://github.com/fivetran/dbt_pendo/issues/10).

**Comment by fivetran-joemarkiewicz** [comment]
Thanks so much for opening this PR @everettttt 💯 

These changes look great. I will just make a small update to reflect the version change and also add your contribution to our CHANGELOG.md. In the meantime, would you be able to confirm that these changes do in fact resolve the issue you identified?

**Comment by fivetran-joemarkiewicz** [comment]
@everettttt FYI the change has been merged into `main`. We typically have release freezes on Friday afternoons. You can expect the release to be cut and live on Monday. 😄

**Comment by fivetran-joemarkiewicz** [comment]
Hi @everettttt, I hope you had a great weekend! I just wanted to post an update that the release `v0.2.1` of the dbt_pendo_source package has been cut!

You can expect this to be live within the hour. I will close this issue. If this issue continues to persist please feel free to re open the issue. Thanks again for raising this to our attention.
